"""Auxiliary tooling around the joint-control loop: bench tests, trajectory
sources, and the result records they produce."""

from .latency import (
    DEFAULT_STEP_DEG,
    DEFAULT_TRIALS,
    LatencySummary,
    LatencyTrial,
    measure_latency,
    summarize_latency,
)
from .loop_trace import (
    DEFAULT_TEMP_HZ,
    DEFAULT_TRACE_HZ,
    JointTrace,
    LoopTracer,
    TraceSummary,
)
from .waypoint_runner import (
    DEFAULT_ARRIVAL_TOLERANCE_DEG,
    DEFAULT_START_GRACE_S,
    DEFAULT_START_TRAVEL_DEG,
    DEFAULT_DWELL_CHECKPOINTS_S,
    DEFAULT_IN_TOLERANCE_DEG,
    DEFAULT_MOTION_THRESHOLD_DEG,
    DEFAULT_POLL_HZ,
    DEFAULT_SETTLE_DWELL_S,
    DEFAULT_SETTLE_WINDOW_S,
    DEFAULT_TARGET_INSET,
    DEFAULT_WAYPOINT_TIMEOUT_S,
    JointOutcome,
    RandomWaypoints,
    TrajectoryWaypoints,
    WaypointRecord,
    available_fingers,
    finger_joints,
    joint_target_range,
    read_trajectory_csv,
    resolve_joints,
    run_waypoint_test,
    write_results_csv,
)
from .command_pacing import (
    LATE_MULTIPLE,
    STALL_MULTIPLE,
    PacingMonitor,
    PacingStats,
)
from .waypoint_stats import (
    JointStats,
    RunStats,
    summarize_run,
    write_stats_csv,
)

__all__ = [
    "DEFAULT_ARRIVAL_TOLERANCE_DEG",
    "DEFAULT_START_GRACE_S",
    "DEFAULT_START_TRAVEL_DEG",
    "DEFAULT_DWELL_CHECKPOINTS_S",
    "DEFAULT_IN_TOLERANCE_DEG",
    "DEFAULT_MOTION_THRESHOLD_DEG",
    "DEFAULT_POLL_HZ",
    "DEFAULT_SETTLE_DWELL_S",
    "DEFAULT_SETTLE_WINDOW_S",
    "DEFAULT_TARGET_INSET",
    "DEFAULT_WAYPOINT_TIMEOUT_S",
    "JointOutcome",
    "RandomWaypoints",
    "TrajectoryWaypoints",
    "WaypointRecord",
    "available_fingers",
    "finger_joints",
    "joint_target_range",
    "read_trajectory_csv",
    "resolve_joints",
    "run_waypoint_test",
    "write_results_csv",
    "DEFAULT_STEP_DEG",
    "DEFAULT_TRIALS",
    "LatencySummary",
    "LatencyTrial",
    "measure_latency",
    "summarize_latency",
    "DEFAULT_TEMP_HZ",
    "DEFAULT_TRACE_HZ",
    "JointTrace",
    "LoopTracer",
    "TraceSummary",
    "LATE_MULTIPLE",
    "STALL_MULTIPLE",
    "PacingMonitor",
    "PacingStats",
    "JointStats",
    "RunStats",
    "summarize_run",
    "write_stats_csv",
]
