port: /dev/ttyUSB0
model: lite
motor_type: feetech
version: 0.1.0
baudrate: 1000000
max_current: 400
type: right
control_mode: current_based_position
motor_ids:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
joint_ids:
- thumb_cmc
- thumb_abd
- thumb_mcp
- thumb_pip
- index_abd
- index_mcp
- index_pip
- middle_abd
- middle_mcp
- middle_pip
- ring_abd
- ring_mcp
- ring_pip
- pinky_abd
- pinky_mcp
- pinky_pip
- wrist
joint_properties:
  thumb_cmc:
    actuation: bidirectional
    inverted: true
  thumb_abd:
    actuation: bidirectional
    inverted: true
  thumb_mcp:
    actuation: unidirectional
    motor_direction: flex
  thumb_pip:
    actuation: passive
  index_abd:
    actuation: unidirectional
    motor_direction: flex
    inverted: true
  index_mcp:
    actuation: bidirectional
    inverted: true
  index_pip:
    actuation: unidirectional
    motor_direction: flex
    inverted: true
  middle_abd:
    actuation: fixed
  middle_mcp:
    actuation: unidirectional
    motor_direction: flex
  middle_pip:
    actuation: passive
  ring_abd:
    actuation: fixed
  ring_mcp:
    actuation: unidirectional
    motor_direction: flex
  ring_pip:
    actuation: passive
  pinky_abd:
    actuation: unidirectional
    motor_direction: extend
    inverted: true  # Add this to reverse the motor direction
  pinky_mcp:
    actuation: unidirectional
    motor_direction: flex
  pinky_pip:
    actuation: passive
  wrist:
    actuation: bidirectional
    inverted: true
motor_to_joint_map:
  1:
  - index_pip
  2:
  - thumb_mcp
  - thumb_pip
  3:
  - ring_mcp
  - ring_pip
  - pinky_mcp
  - pinky_pip
  4:
  - index_abd
  - pinky_abd
  5:
  - middle_mcp
  - middle_pip
  6:
  - wrist
  7:
  - thumb_cmc
  8:
  - thumb_abd
  9:
  - index_mcp
joint_roms:
  thumb_cmc:
  - -45
  - 33
  thumb_abd:
  - -18
  - 55
  thumb_mcp:
  - 0
  - 100
  thumb_pip:
  - 0
  - 107
  index_abd:
  - -10
  - 30
  index_mcp:
  - 0
  - 100
  index_pip:
  - 0
  - 107
  middle_abd:
  - 0
  - 0
  middle_mcp:
  - 0
  - 100
  middle_pip:
  - 0
  - 107
  ring_abd:
  - 0
  - 0
  ring_mcp:
  - 0
  - 100
  ring_pip:
  - 0
  - 107
  pinky_abd:
  - -10
  - 30
  pinky_mcp:
  - 0
  - 100
  pinky_pip:
  - 0
  - 107
  wrist:
  - -65
  - 35
neutral_position:
  thumb_cmc: 0
  thumb_abd: 0
  thumb_mcp: 0
  thumb_pip: 0
  index_abd: 0
  index_mcp: 0
  index_pip: 0
  middle_abd: 0
  middle_mcp: 0
  middle_pip: 0
  ring_abd: 0
  ring_mcp: 0
  ring_pip: 0
  pinky_abd: 0
  pinky_mcp: 0
  pinky_pip: 0
  wrist: 0
calib_current: 350
calib_step_size: 0.1
calib_step_period: 0.001
calib_num_stable: 10
calib_threshold: 0.01
tension_threshold: 30
tension_approach_period: 0.2
motor_range_estimate:
  1: 2.6
  2: 3
  3: 2
  4: 0.2
  5: 4
calib_sequence:
- thumb_cmc
- thumb_abd
- thumb_mcp
- index_abd
- index_mcp
- index_pip
- middle_mcp
- ring_mcp
- wrist